### ISSUE TITLE
Issue deploying my own token

### ISSUE THREAD

**Issue by makemesteaks** [raiden-network/microraiden#123]
Hello,
I am having issues deploying my token based on your contracts.

(env) root@ip-172-31-52-247:/home/ubuntu/microraiden_final/microraiden/contracts# python deploy/deploy_testnet.py --chain kovan --owner  0x6017275B96140b2B8F30eD7d1785D31D26a8bF91 --token-name ERC223Token --token-decimals 18 --token-symbol TST

Make sure kovan chain is running, you can connect to it and it is synced, or you'll get timeout
Web3 provider is RPC connection http://127.0.0.1:8545

ERC223Token  address is 0xd1af2920b454dae0816214c6b564f8ea3c1e5e3c

Traceback (most recent call last):
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8545): Read timed out. (read timeout=180)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deploy/deploy_testnet.py", line 179, in <module>
    print(getTokens())
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "deploy/deploy_testnet.py", line 131, in getTokens
    txhash = channel_factory.deploy(args=[token_address, challenge_period])
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/web3/contract.py", line 310, in deploy
    txn_hash = cls.web3.eth.sendTransaction(deploy_transaction)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/web3/eth.py", line 249, in sendTransaction
    [formatters.input_transaction_formatter(self, formatted_transaction)],
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/web3/providers/manager.py", line 27, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/web3/providers/rpc.py", line 52, in make_request
    **self.get_request_kwargs()
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/microraiden_final/microraiden/env/lib/python3.5/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8545): Read timed out. (read timeout=180)

Kovan is synced and working correctly with Microraiden, although it gives me a read time out when trying to deploy.

**Comment by loredanacirstea** [comment]
Hi, what happens if you change the timeout value for `kovan` from `180` to something bigger - e.g. `360`?

https://github.com/raiden-network/microraiden/blob/master/contracts/populus.json#L184

**Comment by loredanacirstea** [comment]
I think your account is locked. Check the commands for running the chains: https://github.com/raiden-network/microraiden/blob/master/contracts/README.md#chain-setup

especially:
```
--unlock 0x6017275B96140b2B8F30eD7d1785D31D26a8bF91 --password ~/password.txt
```

If this is the issue, please let me know. I would however keep this open - a check for the existence of the account & locked/unlocked state should be implemented.

**Comment by makemesteaks** [comment]
Hello,

I am using parity with the account unlocked. I can use microraiden channels without any issue, just when I am trying to deploy the token I get the timeout.

**Comment by makemesteaks** [comment]
Hello,
Problem solved.
I just had to edit the populus.json with the correct account :-)
Thank you
