### ISSUE TITLE
Unstable state makes proxy quits with `Python int too large to convert to SQLite INTEGER`

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/microraiden#206]
Even after removing `~/.config/microraiden`, on initial scan, after reaching given block, server crashes with following exception:
```
DEBUG:blockchain:filtering for events u:4800000-4897496 c:4799999-4897495 @4897496
DEBUG:blockchain:received unconfirmed ChannelOpened event (sender 0xe0902284c85a9a03daa3b5ab032e238cc05cff9a, block number 4896329)
Traceback (most recent call last):
  File "/sec/Dev/BrainBot/microraiden/virtualenv3/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/sec/Dev/BrainBot/microraiden/microraiden/microraiden/channel_manager/blockchain.py", line 29, in _run
    self._update()
  File "/sec/Dev/BrainBot/microraiden/microraiden/microraiden/channel_manager/blockchain.py", line 115, in _update
    self.cm.unconfirmed_event_channel_opened(sender, open_block_number, deposit)
  File "/sec/Dev/BrainBot/microraiden/microraiden/microraiden/channel_manager/manager.py", line 124, in unconfirmed_event_channel_opened
    self.state.set_channel(c)
  File "/sec/Dev/BrainBot/microraiden/microraiden/microraiden/channel_manager/state.py", line 280, in set_channel
    self.add_channel(channel)
  File "/sec/Dev/BrainBot/microraiden/microraiden/microraiden/channel_manager/state.py", line 314, in add_channel
    self.conn.execute(ADD_CHANNEL_SQL, params)
OverflowError: Python int too large to convert to SQLite INTEGER
Tue Nov 28 18:39:52 2017 <Blockchain at 0x7f57c9d62cc0> failed with OverflowError

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/sec/Dev/BrainBot/microraiden/microraiden/microraiden/examples/demo_proxy/__main__.py", line 55, in <module>
    main()
  File "/sec/Dev/BrainBot/microraiden/virtualenv3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
...
  File "/sec/Dev/BrainBot/microraiden/virtualenv3/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7f57c9d629c8 epoll default pending=0 ref=0 fileno=3 resolver=<gevent.resolver_thread.Resolver at 0x7f57c9cf3c50 pool=<ThreadPool at 0x7f57c9cf3c18 0/1/10>> threadpool=<ThreadPool at 0x7f57c9cf3c18 0/1/10>>)
```

Account is unusable then, because proxy always have to go through this block. It's critical, as it could cause a DoS in the server, allowing clients to cheat while server is offline.

Tested with [andrevmatos/microraiden/tree/typescript](https://github.com/andrevmatos/microraiden/tree/typescript) from #151, rebased on current master (a7631035686a4f60bb3db003fad14048b20aa8c9)

**Comment by pcppcp** [comment]
@andrevmatos I've used `DECIMAL(78,0)` for the balances - this should be enough to fit uint256. It's crazy big number though :)

**Comment by andrevmatos** [comment]
@pcppcp Ok, nice. Just for you to know, Sqlite doesn't actually enforce the precision on numeric types, it just stores everything in it's internal representation, it's more for documentation purposes, but it's right to write it as the required precision.
