### ISSUE TITLE
`microraiden.proxy` keeps sending payment headers, even if no `Blockchain` connection is available

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/microraiden#238]
If the `Blockchain` connection of the proxy server died, e.g. because of `InsufficientFunds` for a challenge transaction, the server keeps responding with `402` payment headers to client requests. 

A gullible client may keep sending payments or topping up the channel in such a case.

The proxy server should instead send a `500`, if it is not able to check channel balances anymore.

```
# this killed the `Blockchain` instance
DEBUG:blockchain:received ChannelCloseRequested event (sender 0x753aed39796866c7f9a1fe35a4ef72fe0857a167, block number 4933181) 
INFO:channel_manager:sender tried to cheat, sending challenge (sender 0x753aed39796866c7f9a1fe35a4ef72fe0857a167, block number 4933181) 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/microraiden/microraiden/microraiden/channel_manager/blockchain.py", line 29, in _run
    self._update()
  File "/microraiden/microraiden/microraiden/channel_manager/blockchain.py", line 195, in _update
    self.cm.event_channel_close_requested(sender, open_block_number, balance, timeout)
  File "/microraiden/microraiden/microraiden/channel_manager/manager.py", line 140, in event_channel_close_requested
    self.close_channel(sender, open_block_number)  # dispute by closing the channel
  File "/microraiden/microraiden/microraiden/channel_manager/manager.py", line 211, in close_channel
    txid = self.blockchain.web3.eth.sendRawTransaction(raw_tx)
  File "/usr/local/lib/python3.5/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/site-packages/web3/eth.py", line 256, in sendRawTransaction
    [raw_transaction],
  File "/usr/local/lib/python3.5/site-packages/web3/providers/manager.py", line 35, in request_blocking
    raise ValueError(response["error"])
ValueError: {'message': 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 5000000000000000 and got: 0.', 'code': -32010}
Fri Dec  1 16:21:36 2017 <Blockchain at 0x7fabe70ec930> failed with ValueError

# proxy happily answers 402 afterwards
172.20.0.2 - - [2017-12-01 16:32:50] "GET /something HTTP/1.1" 402 392 0.004411
INFO:microraiden.proxy.resources.expensive:something 
172.20.0.2 - - [2017-12-01 16:32:55] "GET /something HTTP/1.1" 402 392 0.007853
INFO:microraiden.proxy.resources.expensive:something 
172.20.0.2 - - [2017-12-01 16:33:09] "GET /something HTTP/1.1" 402 392 0.003446
INFO:microraiden.proxy.resources.expensive:something 
172.20.0.2 - - [2017-12-01 16:33:14] "GET /something HTTP/1.1" 402 392 0.005636
[...]
```

**Comment by pcppcp** [comment]
Uh, oh. I'll fix that. Sure it should reply internal sever error in this case and blockchain should recover.
