### ISSUE TITLE
channel manager dies if eth node doesn't respond

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/microraiden#294]
```
Traceback (most recent call last):
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/xoza/src/micropay/raiden-micropayment-service/microraiden/microraiden/channel_manager/blockchain.py", line 51, in _run
    self._update()
  File "/home/xoza/src/micropay/raiden-micropayment-service/microraiden/microraiden/channel_manager/blockchain.py", line 72, in _update
    current_block = self.web3.eth.blockNumber
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/utils/functional.py", line 14, in inner
    value = fn(*args, **kwargs)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/eth.py", line 110, in blockNumber
    return self.web3._requestManager.request_blocking("eth_blockNumber", [])
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/providers/manager.py", line 27, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/providers/rpc.py", line 52, in make_request
    **self.get_request_kwargs()
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8545): Read timed out. (read timeout=60)
```

**Comment by patricklenert** [comment]
How did you solve this bug?
