### ISSUE TITLE
microraiden.examples.wikipaydia error 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by sadaf2605** [raiden-network/microraiden#321]
python3 -m microraiden.examples.wikipaydia --private-key ../../api/pk2.csv  --rpc-provider https://kovan.infura.io/Ug2W9nZzjwN4lITvvLT0   start

WARNING:microraiden.utils:Private key in raw format. Consider switching to JSON-encoded 
INFO:filelock:Lock 4511055320 acquired on /Users/sadafnoor/Library/Application Support/microraiden/0xeb8f0c65_0x5b9829a8.db.lock 
DEBUG:channel_manager:setting up channel manager, receiver=0x5b9829a8ac3960d2f3745ef2967fc798abd9bb42 channel_contract=0xeb8f0c65921c6f2b6025d9dbdd9466419cbe56ec 
INFO:blockchain:starting blockchain polling (interval 2s) 
DEBUG:blockchain:filtering for events u:5194944-5194951 c:5194943-5194950 @5194951 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/sadafnoor/Projects/machaao_mr/microraiden/microraiden/microraiden/channel_manager/blockchain.py", line 29, in _run
    self._update()
  File "/Users/sadafnoor/Projects/machaao_mr/microraiden/microraiden/microraiden/channel_manager/blockchain.py", line 68, in _update
    self.web3.eth.getBlock(self.cm.state.confirmed_head_hash)
  File "/usr/local/lib/python3.6/site-packages/web3/utils/functional.py", line 15, in inner
    return formatter(value)
  File "/usr/local/lib/python3.6/site-packages/web3/formatters.py", line 84, in wrapped
    return wrapper(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/web3/formatters.py", line 235, in output_block_formatter
    for key, value in block.items()
AttributeError: 'NoneType' object has no attribute 'items'
Mon Jan  1 18:05:39 2018 <Blockchain at 0x10c6c7340> failed with AttributeError

**Comment by pcppcp** [comment]
Hi Sadaf,
This is similar to an already fixed bug #82 
Can you post your configuration? (uRaiden changeset and `pip freeze` output should be enough)

**Comment by pcppcp** [comment]
Ha, it seems you are using Infura - we haven't really tested uRaiden with this backend. 
There's an open PR #320 that adds support for it, but so far it still needs more testing. Infura seems to not return events reliably and thus uRaiden sometimes fails to register open channel.
