### ISSUE TITLE
microraiden.client.client Client returns ValueError: No matching functions found

### ISSUE THREAD

**Issue by sadaf2605** [raiden-network/microraiden#323]
I have following code on both kovan and mainnet:
```
with Client(privkey, 
channel_manager_proxy = channel_manager_proxy
) as client:

    channel = client.get_suitable_channel(receiver, 10)

```
I am getting following error:
```
Traceback (most recent call last):
  File "test.py", line 150, in <module>
    channel_manager_proxy = channel_manager_proxy
  File "/Users/sadafnoor/Projects/machaao_mr/microraiden/microraiden/microraiden/client/client.py", line 96, in __init__
    token_address = self.channel_manager_proxy.contract.call().token_address()
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 769, in call_contract_function
    transaction=transaction,
  File "/usr/local/lib/python3.6/site-packages/web3/utils/decorators.py", line 12, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 691, in _prepare_transaction
    fn_kwargs,
  File "/usr/local/lib/python3.6/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 730, in _encode_transaction_data
    fn_name, args, kwargs,
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 659, in _get_function_info
    fn_abi = cls._find_matching_fn_abi(fn_name, args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 623, in _find_matching_fn_abi
    raise ValueError("No matching functions found")
ValueError: No matching functions found
```

**Comment by devium** [comment]
Looks like you're using an outdated version of µRaiden. We'll be releasing a new version soon that improves usability a lot and fixes stuff like this. Meanwhile, please base your work on master.
