### ISSUE TITLE
deploying microraiden on Rinkeby

### ISSUE THREAD

**Issue by sbaks0820** [raiden-network/microraiden#414]
I'm trying to get deploy the contracts for microraiden on Rinkeby according to the instructions [in the docs](http://microraiden.readthedocs.io/en/latest/contract/index.html#opening-a-transfer-channel). But I encounter the following error executing 
```
python3 -m deploy.deploy_testnet --chain rinkeby --owner 0xe5e3a76c406321e15039dadccb1224e49776592d --supply 1000000 --token-decimals 18 --challenge-period 500 --token-name CustomToken --token-symbol FCK
```

```
Make sure rinkeby chain is running, you can connect to it and it is synced,
          or you'll get timeout
Web3 provider is RPC connection http://172.19.0.17:8745
Owner is 0xe5e3a76c406321e15039daDcCB1224e49776592D
Traceback (most recent call last):
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/utils/formatters.py", line 66, in apply_formatters_to_dict
    yield key, formatters[key](item)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/middleware/pythonic.py", line 94, in to_hexbytes
    result, len(result), num_bytes
ValueError: The value HexBytes('0xd783010800846765746887676f312e392e32856c696e75780000000000000000913a63403b7083000106cd0be9b41c9aa772cb28530d6bf732ba57c8f77088db2a0e6edcdb03e494e85b4e4964053f9a5822714fa02bf25dfecefb2325adece701') is 97 bytes, but should be 32

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/suryab/projects/thesis/microraiden/contracts/deploy/deploy_testnet.py", line 113, in <module>
    main()
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/suryab/projects/thesis/microraiden/contracts/deploy/deploy_testnet.py", line 92, in main
    transaction={'from': owner}
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/contract.py", line 247, in deploy
    txn_hash = cls.web3.eth.sendTransaction(deploy_transaction)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/eth.py", line 206, in sendTransaction
    get_buffered_gas_estimate(self.web3, transaction),
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/utils/transactions.py", line 161, in get_buffered_gas_estimate
    gas_limit = get_block_gas_limit(web3)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/utils/transactions.py", line 152, in get_block_gas_limit
    block = web3.eth.getBlock(block_identifier)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/eth.py", line 122, in getBlock
    [block_identifier, full_transactions],
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/manager.py", line 96, in request_blocking
    response = self._make_request(method, params)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/manager.py", line 79, in _make_request
    return request_func(method, params)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 20, in middleware
    response = make_request(method, params)
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/middleware/formatting.py", line 30, in middleware
    formatter(response['result']),
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/utils/formatters.py", line 55, in apply_formatter_if
    return formatter(value)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/suryab/projects/thesis/env/lib/python3.6/site-packages/web3/utils/formatters.py", line 68, in apply_formatters_to_dict
    raise type(exc)("Could not format value %r as field %r" % (item, key)) from exc
ValueError: Could not format value '0xd783010800846765746887676f312e392e32856c696e75780000000000000000913a63403b7083000106cd0be9b41c9aa772cb28530d6bf732ba57c8f77088db2a0e6edcdb03e494e85b4e4964053f9a5822714fa02bf25dfecefb2325adece701' as field 'extraData'
```

I'm running this on `Ubuntu 16.04` with `python 3.6`. I've installed all of the requirements from `requirements.txt` and all tests from `pytest` pass.

**Comment by sbaks0820** [comment]
Don't know if this is something that's been encountered before, but figured I'd ask here.

**Comment by loredanacirstea** [comment]
@sbaks0820 , until https://github.com/raiden-network/microraiden/pull/416 is merged, you can take a look at the changes and test them.

This is a PoA issue with adding bytes to `extraData`. See PR description.

**Comment by sbaks0820** [comment]
I used his commits and was able to deploy the contracts. Thanks!

**Comment by sbaks0820** [comment]
This same problem arises when just trying to run the `echo_server.py` from the examples. The pull request really only fixes it for testnet deployment. It's not straightforward to me how to fix this for the blockchain utility but I'll give it a shot.

**Comment by loredanacirstea** [comment]
@sbaks0820 , because this is a PoA & web3.py issue, it is unlikely that we will implement a fix for this problem - which would be temporary anyway. Yes, you can try to add the changes from the above PR in blockchain.py or even in https://github.com/raiden-network/microraiden/blob/master/microraiden/microraiden/click_helpers.py.
