### ISSUE TITLE
Issue when starting examples

### ISSUE THREAD

**Issue by MartinOpde** [raiden-network/microraiden#449]
I can't start examples.  I get : `TypeError: The 'data' value must be of bytes type.  Got <class 'str'>`

Here is the full stacktrace :
`Martins-MacBook-Pro:microraiden martin$ python -m microraiden.examples.ticker_proxy --private-key /Users/martin/Library/Ethereum/rinkeby/keystore/UTC--2018-02-22T09-37-3793393000Z--476b3c2339094daaae3255c66616fe6e437e90c2 start
Enter the private key password: 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/martin/Desktop/microraiden/microraiden/examples/ticker_proxy.py", line 63, in <module>
    main()
  File "/Users/martin/Desktop/microraiden/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/martin/Desktop/microraiden/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/martin/Desktop/microraiden/venv/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/martin/Desktop/microraiden/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/martin/Desktop/microraiden/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/martin/Desktop/microraiden/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/martin/Desktop/microraiden/microraiden/click_helpers.py", line 139, in main
    web3=web3)
  File "/Users/martin/Desktop/microraiden/microraiden/make_helpers.py", line 108, in make_paywalled_proxy
    channel_manager = make_channel_manager(private_key, contract_address, state_filename, web3)
  File "/Users/martin/Desktop/microraiden/microraiden/make_helpers.py", line 58, in make_channel_manager
    token_address = channel_manager_contract.call().token()
  File "/Users/martin/Desktop/microraiden/venv/lib/python3.6/site-packages/web3/contract.py", line 794, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/Users/martin/Desktop/microraiden/venv/lib/python3.6/site-packages/eth_abi/abi.py", line 58, in decode_abi
    raise TypeError("The `data` value must be of bytes type.  Got {0}".format(type(data)))
TypeError: The `data` value must be of bytes type.  Got <class 'str'>`

I am running on macOS

**Comment by loredanacirstea** [comment]
@MartinOpde , please check the new pypi release from this morning : `0.2.5`. Otherwise, please try it with `eth-abi==0.5.0`.

**Comment by MartinOpde** [comment]
Thank you, it works after I upgraded from 0.2.4 to 0.2.5

**Comment by loredanacirstea** [comment]
Closing this issue then.
Happy testing!
