### ISSUE TITLE
Cannot run echo server

### ISSUE THREAD

**Issue by elaine030490** [raiden-network/microraiden#488]
I'm trying to run the echo service example mentioned here - https://microraiden.readthedocs.io/en/latest/tutorials/try-echo-service.html
I've completed the microraiden installation and set up geth as per the instructions.

When I run the command to start the microraiden receiver- 
python microraiden/examples/echo_server.py --private-key microraiden/examples/pk_tut.txt,
I get the following error - 

```Traceback (most recent call last):
  File "/home/harshreddy/env/lib/python3.6/site-packages/web3/contract.py", line 794, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/home/harshreddy/env/lib/python3.6/site-packages/eth_abi/abi.py", line 109, in decode_abi
    return decoder(stream)
  File "/home/harshreddy/env/lib/python3.6/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "/home/harshreddy/env/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/harshreddy/env/lib/python3.6/site-packages/eth_abi/decoding.py", line 140, in decode
    yield decoder(stream)
  File "/home/harshreddy/env/lib/python3.6/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "/home/harshreddy/env/lib/python3.6/site-packages/eth_abi/decoding.py", line 165, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "/home/harshreddy/env/lib/python3.6/site-packages/eth_abi/decoding.py", line 247, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "microraiden/examples/echo_server.py", line 99, in <module>
    main()
  File "/home/harshreddy/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/harshreddy/env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/harshreddy/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harshreddy/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "microraiden/examples/echo_server.py", line 47, in main
    run(private_key)
  File "microraiden/examples/echo_server.py", line 71, in run
    web3
  File "/home/harshreddy/microraiden/microraiden/make_helpers.py", line 59, in make_channel_manager
    token_address = channel_manager_contract.call().token()
  File "/home/harshreddy/env/lib/python3.6/site-packages/web3/contract.py", line 816, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
```
I'm running on Ubuntu 18.04.1 LTS

**Comment by msaxena18** [comment]
I tried using Geth as well. It takes a long time to sync. I recommend downloading parity instead and using that. It still took me about 3 hours to sync fully. You can download parity from here: https://wiki.parity.io/Setup . After it syncs, you shouldn't be getting that error.

**Comment by patricklenert** [comment]
I had the same problem and @msaxena18 is right. Use Parity and type in the command console "**parity --light --cache-size 1024 —chain ropsten --rpcport=8545**". This will be the fastest way to sync with ethereum. 

Now I have a new problem: I get `ValueError: {'code': -32041, 'message': 'Requested data size exceeds limit of 1000 blocks.'}` 
_and_ 
`gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x10ccc5930 select default pending=0 ref=0>)`

What could possibly be the solution?
