### ISSUE TITLE
State sync fails if ethereum node's blockchain isn't completely synced

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/microraiden#82]
If parity isn't fully synced, it can return `null` result for a not-yet-synced ancient block.
This will confuse `web3` library, causing app to fail.

Tcpdump
```
POST / HTTP/1.1
Host: localhost:8545
User-Agent: Web3.py/3.11.1/<class 'web3.providers.rpc.HTTPProvider'>
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Type: application/json
Content-Length: 92

{"id": 35, "jsonrpc": "2.0", "params": ["0x61a7f", false], "method": "eth_getBlockByNumber"}
16:04:29.644464 IP 127.0.0.1.8545 > 127.0.0.1.34690: Flags [P.], seq 16319:16481, ack 17306, win 659, options [nop,nop,TS val 83769140 ecr 83769140], length 162
E.....@.@.~\........!a..	..$|V.............
..74..74HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 12 Sep 2017 14:04:29 GMT
Transfer-Encoding: chunked

28
{"jsonrpc":"2.0","result":null,"id":35}
```
App traceback
```pytb
Traceback (most recent call last):
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/xoza/src/micropay/raiden-micropayment-service/microraiden/microraiden/channel_manager.py", line 58, in _run
    self._update()
  File "/home/xoza/src/micropay/raiden-micropayment-service/microraiden/microraiden/channel_manager.py", line 215, in _update
    new_unconfirmed_head_hash = self.web3.eth.getBlock(new_unconfirmed_head_number).hash
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/utils/functional.py", line 15, in inner
    return formatter(value)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/formatters.py", line 84, in wrapped
    return wrapper(fn(*args, **kwargs))
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/formatters.py", line 235, in output_block_formatter
    for key, value in block.items()
AttributeError: 'NoneType' object has no attribute 'items'
Tue Sep 12 16:05:44 2017 <Blockchain at 0x7fc4a89bfd58> failed with AttributeError

Traceback (most recent call last):
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/xoza/src/micropay/raiden-micropayment-service/microraiden/microraiden/channel_manager.py", line 339, in _run
    self.blockchain.get()  # re-raises exception
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/gevent/greenlet.py", line 482, in get
    self._raise_exception()
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/gevent/greenlet.py", line 159, in _raise_exception
    reraise(*self.exc_info)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/gevent/_compat.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/xoza/src/micropay/raiden-micropayment-service/microraiden/microraiden/channel_manager.py", line 58, in _run
    self._update()
  File "/home/xoza/src/micropay/raiden-micropayment-service/microraiden/microraiden/channel_manager.py", line 215, in _update
    new_unconfirmed_head_hash = self.web3.eth.getBlock(new_unconfirmed_head_number).hash
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/utils/functional.py", line 15, in inner
    return formatter(value)
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/formatters.py", line 84, in wrapped
    return wrapper(fn(*args, **kwargs))
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/xoza/src/micropay/lib/python3.4/site-packages/web3/formatters.py", line 235, in output_block_formatter
    for key, value in block.items()
AttributeError: 'NoneType' object has no attribute 'items'
Tue Sep 12 16:05:44 2017 <ChannelManager at 0x7fc4a8a136d0> failed with AttributeError
```

**Comment by pcppcp** [comment]
Closing this as uRaiden will now refuse to start if the node isn't synced. In such case, an error message explaining the problem is displayed to the user.
